0xB10C/peer-observer

Cargo.lock
extractor/Cargo.toml
extractor/build.rs

See also #15. This requires rustc 1.71 which might not be available for NixOS yet.

update: libbpf 0.22 -> 0.23

---

extractor/src/main.rs
shared/src/ctypes.rs

On some systems, allocating an array for a "HUGE" P2P message (4 MB) payload failed due to it being larger than the rust default stack size of 2 MB.
To fix this, use a vector (allocated on the heap) instead of an array. This also allows some memory savings for "huge" messages that aren't actually 4MB in size as we can use the metadata size instead.
A test for huge messages is introduced to add test coverage for this bug.

fix: avoid stack overflows with "huge" P2P messages

---

Cargo.lock
Cargo.toml
shared/Cargo.toml
shared/build.rs
shared/src/lib.rs
tools/addr-connectivity-rs/Cargo.toml
tools/addr-connectivity-rs/src/main.rs
tools/logger/Cargo.toml
tools/logger/src/main.rs
tools/metrics/Cargo.toml
tools/metrics/src/main.rs
tools/websocket/Cargo.toml
tools/websocket/src/main.rs

Sends out the events as JSON messages via WebSocket
The current implementation needs some clean up. This is primarily a proof-of-concept.

Add websocket tool

---

Cargo.lock

Currently, the CI on Ubuntu fails with:
```
error[E0282]: type annotations needed for `Box<_>`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```
Updating time with `cargo update -p time` should fix it.

update: 'time' dependency

---

.github/workflows/rust-ubuntu.yml

Also renames `rust.yml` to `rust-ubuntu.yml`.

update: ubuntu ci checkout v3 -> v4

---

Cargo.lock
extractor/Cargo.toml
extractor/src/main.rs

As noticed by @i-am-yuvi recently, bumping the rlimit is not required (anymore).
It turns out that, since libbpf commit https://github.com/libbpf/libbpf/commit/216eaa760edf06f3521d5d49a419515607c1f38e, the rlimit bump in downstream applications isn't needed anymore as libbpf handles it, if needed.

remove rlimit bumping in extractor

---

Cargo.lock
extractor/src/main.rs
shared/Cargo.toml
shared/src/lib.rs
tools/connectivity-check/src/main.rs
tools/logger/src/main.rs
tools/metrics/src/main.rs

Fixes #28.
The clap-based command line arguments not provide a `--help`, `--version`, and usage hints. It's also explicit what's needed and what's used as default.
For example, the extractor help now shows:
```
$ extractor --help
The peer-observer extractor Hooks into a Bitcoin Core binary with tracepoints and extracts events from it into a nanomsg PUB-SUB queue
Usage: extractor [OPTIONS] --bitcoind-path <BITCOIND_PATH>
Options:
-a, --address <ADDRESS>              TCP socket the nanomsg publisher binds on [default: tcp://127.0.0.1:8883]
-b, --bitcoind-path <BITCOIND_PATH>  Path to the Bitcoin Core (bitcoind) binary that should be hooked into
--no-p2pmsg-tracepoints          Controls if the p2p message tracepoints should be hooked into
--no-connection-tracepoints      Controls if the …
```

Use clap for command line arguments

---

tools/metrics/src/main.rs
tools/metrics/src/metrics.rs

```
peerobserver_conn_closed_age_seconds 67
```
closes https://github.com/0xB10C/peer-observer/issues/35

add: closed connection age counter metric

---

Cargo.lock
extractor/src/main.rs
shared/Cargo.toml
shared/src/ctypes.rs
shared/src/lib.rs
tools/connectivity-check/Cargo.toml
tools/connectivity-check/src/main.rs
tools/connectivity-check/src/metricserver.rs
tools/logger/src/main.rs
tools/metrics/Cargo.toml
tools/metrics/src/main.rs
tools/metrics/src/metricserver.rs
tools/websocket/src/main.rs

flowing up on https://github.com/0xB10C/peer-observer/pull/42
from #46: 
Closes https://github.com/0xB10C/peer-observer/issues/46

Improve logging of tools and extractor

---

Cargo.lock
extractor/Cargo.toml
extractor/src/main.rs
shared/Cargo.toml
shared/src/lib.rs
tools/connectivity-check/Cargo.toml
tools/connectivity-check/src/main.rs
tools/logger/Cargo.toml
tools/logger/src/main.rs
tools/metrics/Cargo.toml
tools/metrics/src/main.rs
tools/websocket/Cargo.toml
tools/websocket/src/main.rs

Allows us to update everything in one place and makes sure the extractor and all tools always have the same version.
closes https://github.com/0xB10C/peer-observer/issues/47

refactor: extract nng crate to shared module

---

extractor/src/main.rs
tools/connectivity-check/src/main.rs
tools/logger/src/main.rs
tools/metrics/src/main.rs

- the arg struct comments have to be `///` to show up in the --help output of the binary
- the metrics tool didn't have a log level argument

a few clap and logging fixups

---

extractor/src/main.rs

Partly addresses #58
This is optional for now but will become required if  bitcoin/bitcoin/26593 is merged.

add: cli arg to specify a bitcoind PID

---

shell.nix

fixes:
```
error: 'bpftool' has been renamed to/replaced by 'bpftools'
```

update: rename bpftool -> bpftools in shell.nix

---

Cargo.lock
README.md
extractor/src/error.rs
extractor/src/main.rs
shared/Cargo.toml
shared/src/lib.rs
shared/src/nats_subjects.rs
tools/connectivity-check/src/main.rs
tools/logger/src/main.rs
tools/metrics/src/main.rs
tools/websocket/src/main.rs

This replaces nanomsg with a NATS-based message queue.
Closes #56

Replace nanomsg (nng) with a NATS-based message queue

---

extractor/src/bpf/tracing.bpf.c

instead of `bpf_probe_read_str()` and `bpf_probe_read()` as recommended by
https://man7.org/linux/man-pages/man7/bpf-helpers.7.html
closes #82

change: use bpf_probe_read_user(_str)

---

tools/logger/src/main.rs

Fixes #48
The logger tool is quite spammy currently as it prints all events
(p2p message, connections, addrman (if enabled), validation, and mempool).
This PR adds a filter where we can pass a command line argument to enable only the desired event types. For example, passing --filter mempool or -f mempool would only log $Mempool messages.

Fix: Add filters to logger tool

---

tools/metrics/src/main.rs
tools/metrics/src/metrics.rs
tools/metrics/src/stat_util.rs

Add more metrics based on data from the `getpeerinfo` RPC

---

tools/metrics/src/main.rs
tools/metrics/src/metrics.rs

Instead of having an extra tool as discussed in #142, do it in the `metrics` tool.
closes #142
Needs some dashboards..

add: prometheus metric for LinkingLion traffic

---

extractors/ebpf/src/main.rs
shared/src/ctypes.rs

- addresses the comments in #21 and closes #21
- cleans up the bitcoind PID handling of the ebpf-extractor: A bitcoind PID is now always required since https://github.com/bitcoin/bitcoin/pull/26593 has been merged (Nov 11, 2024; released in v29.0)

Various ebpf-extractor cleanups

---

tools/connectivity-check/src/metrics.rs

Remove the metric from connectivity-check, because it's currently unused, the docs are wrong, and probably not needed at all.
Also, the CI in https://github.com/0xB10C/peer-observer/pull/222#issuecomment-3193434121 seems to be having problems due to this. Possibly only found by a newer rust version on Ubuntu.

remove unused RUNTIME_START_TIMESTAMP metric from connectivity check tool

---

Cargo.lock
extractors/ebpf/src/error.rs
extractors/ebpf/src/main.rs
shared/Cargo.toml
shared/src/lib.rs

As part of #192, use async_nats instead of the nats create in the ebpf-extractor.
similar to #224 #225 #226

refactor: use async_nats in ebpf-extractor

---

Cargo.lock
extractors/rpc/Cargo.toml
extractors/rpc/README.md
extractors/rpc/src/error.rs
extractors/rpc/src/lib.rs
extractors/rpc/src/main.rs
extractors/rpc/tests/integration.rs
shared/Cargo.toml
shared/src/lib.rs
shell.nix

As part of #26. 
Uses https://crates.io/crates/corepc-node to start two Bitcoin Core nodes.

integration tests for RPC extractor

---

.github/workflows/rust-nix.yml
extractors/ebpf/build.rs
shell.nix

On nixos-unstable:
error: clang_14 has been removed, as it is unmaintained and obsolete

nix: update clang 14 -> 21

---

Cargo.lock
Cargo.toml
README.md
extractors/p2p/Cargo.toml
extractors/p2p/README.md
extractors/p2p/src/error.rs
extractors/p2p/src/lib.rs
extractors/p2p/src/main.rs
extractors/p2p/tests/integration.rs
protobuf/proto-types/event_msg.proto
protobuf/proto-types/p2p_extractor.proto
shared/src/lib.rs
shared/src/nats_subjects.rs
shared/src/p2p_extractor.rs
tools/logger/README.md
tools/logger/src/main.rs
tools/metrics/src/lib.rs
tools/metrics/src/metrics.rs
tools/metrics/tests/integration.rs

This adds a p2p-extractor. The extractor listens on a TCP socket and accepts inbound connections from a Bitcoin node. A Bitcoin node configured with `--addnode=ip:port` will connect (and reconnect) to the extractor. Additionally, the connection will count as a manual connection and not reduce the number of normal outbound (and not inbounds) the node makes. The extractor does only support P2Pv1 for now. This means, the node and the extractor must have the same network magic. The node will open a v2 connection to the p2p-extractor at first, which will be closed. The node will then retry with a v1 connection which then should succeed. 
Currently, the p2p-extractor only sends a ping and measures the time it takes for the node to respond to a pong. When done on localhost (to reduce network …

add: p2p-extractor (initially keeps track of ping-pong durations)

---

Cargo.lock
shared/Cargo.toml

Newer Bitcoin Core versions and e.g. Bitcoin Knots might return fields not present in the corepc-types version used. These previously caused a panic. This was fixed in https://github.com/rust-bitcoin/corepc/pull/367, so use corepc master until there's a new release.
Closes https://github.com/0xB10C/peer-observer/issues/260

fix: rpc-extractor allow extra fields in RPC results
